-- ==============================================================================
-- CAKE N CRAVE - INITIAL PRODUCTS SEED
-- File: supabase/seed.sql
-- ==============================================================================

INSERT INTO public.products (
    id, slug, name, category, flavour_tag, description, price, weight_prices, images, featured, is_new, is_published, is_available, occasions, available_sizes, available_flavours, customization_options, advance_order_notice
) VALUES
(
    'cake-strawberry-dream',
    'strawberry-dream',
    'Strawberry Dream',
    'Cakes',
    'Strawberry',
    'Light and fluffy strawberry cream cake bursting with fresh strawberries and delicate pink frosting. A refreshing delight for any occasion.',
    649,
    '{"0.5 Kg": 649, "1 Kg": 1099, "1.5 Kg": 1537, "2 Kg": 1999, "2.5 Kg": 2449, "3 Kg": 2899}'::jsonb,
    ARRAY['/src/assets/images/strawberry_dream_cake_1790174782027.jpg', '/src/assets/images/hero_cake_display_1790174282202.jpg'],
    true,
    true,
    true,
    true,
    ARRAY['Birthday', 'Anniversary', 'Just Because', 'Mom-to-be'],
    ARRAY['0.5 Kg', '1 Kg', '1.5 Kg', '2 Kg', '2.5 Kg', '3 Kg'],
    ARRAY['Fresh Strawberry Cream', 'Vanilla Strawberry Swirl', 'Strawberry & White Chocolate'],
    ARRAY['Piped Calligraphy Message', 'Golden Acrylic Cake Topper', 'Eggless Edible Pearls'],
    'Please order at least 24 hours in advance'
),
(
    'cake-vintage-lambeth',
    'vintage-lambeth-cake',
    'Vintage Lambeth Heart Cake',
    'Cakes',
    'Vanilla Buttercream',
    'Classic royal Victorian piping with exquisite shell borders, delicate lace ruffles, and maraschino cherries. 100% pure eggless.',
    799,
    '{"0.5 Kg": 799, "1 Kg": 1399, "1.5 Kg": 1949, "2 Kg": 2499}'::jsonb,
    ARRAY['/src/assets/images/hero_cake_display_1790174282202.jpg', '/src/assets/images/strawberry_dream_cake_1790174782027.jpg'],
    true,
    false,
    true,
    true,
    ARRAY['Anniversary', 'Birthday', 'Valentine''s Specials'],
    ARRAY['0.5 Kg', '1 Kg', '1.5 Kg', '2 Kg'],
    ARRAY['Madagascar Vanilla Bean', 'Raspberry Rose Compote', 'Swiss Chocolate Ganache'],
    ARRAY['Custom Heart Calligraphy', 'Ribbon Accents', 'Cherries on Top'],
    'Requires 24-48 hours advance order for intricate Lambeth piping'
),
(
    'cake-belgian-truffle',
    'belgian-dark-truffle-cake',
    'Belgian Dark Truffle Cake',
    'Cakes',
    'Dark Chocolate',
    'Silky 54% dark Belgian chocolate ganache layered with moist cocoa sponge. Decadent, rich, and velvety.',
    749,
    '{"0.5 Kg": 749, "1 Kg": 1299, "1.5 Kg": 1849, "2 Kg": 2399}'::jsonb,
    ARRAY['/src/assets/images/hero_cake_display_1790174282202.jpg'],
    true,
    false,
    true,
    true,
    ARRAY['Birthday', 'Anniversary', 'Celebration'],
    ARRAY['0.5 Kg', '1 Kg', '1.5 Kg', '2 Kg'],
    ARRAY['Pure Belgian 54% Truffle', 'Dark Chocolate Hazelnut', 'Mocha Espresso Ganache'],
    ARRAY['Gold Leaf Flakes', 'Custom Chocolate Plaque', 'Hand-rolled Cocoa Truffles'],
    'Please order at least 24 hours in advance'
),
(
    'bento-korean-daisy',
    'korean-daisy-bento',
    'Korean Daisy Bento Cake',
    'Bento Cakes',
    'Vanilla Rose',
    'Individual minimalist 300g bento cake served in an eco-friendly sugarcane clamshell box. Comes with candle and wooden fork.',
    399,
    '{"Single Bento (300g)": 399}'::jsonb,
    ARRAY['/src/assets/images/bento_cake_collection_1790174295252.jpg'],
    true,
    true,
    true,
    true,
    ARRAY['Birthday', 'Just Because', 'Friendship'],
    ARRAY['Single Bento (300g)'],
    ARRAY['Vanilla Rose Buttercream', 'Lotus Biscoff Crunch', 'Nutella Swirl'],
    ARRAY['Custom 3-Word Lettering', 'Pastel Border Color', 'Complimentary Match & Candle'],
    'Available for same-day delivery if ordered before 2 PM'
),
(
    'hamper-royal-rose',
    'royal-jaipur-hamper',
    'Royal Jaipur Celebration Hamper',
    'Hampers',
    'Assorted Artisanal',
    'A majestic pastel pink gift crate featuring artisanal eggless cookies, a mini bento cake, roasted dry fruits, and fragrant soy candle.',
    1499,
    '{"Luxury Gift Crate": 1499}'::jsonb,
    ARRAY['/src/assets/images/gourmet_gift_hamper_1790174308010.jpg'],
    true,
    false,
    true,
    true,
    ARRAY['Anniversary', 'Corporate', 'Festive', 'Housewarming'],
    ARRAY['Luxury Gift Crate'],
    ARRAY['Chef''s Curated Assortment'],
    ARRAY['Personalized Greeting Card with Wax Seal', 'Silk Satin Ribbon Color'],
    'Please order 24 hours in advance'
),
(
    'bouquet-pink-rose',
    'blush-rose-bouquet',
    'Blush Garden Rose Bouquet',
    'Flower Bouquets',
    'Fresh Florals',
    'Ten pristine pink garden roses hand-tied with gypsophila (baby''s breath) and lush eucalyptus wrapped in matte blush paper.',
    899,
    '{"10 Stems": 899, "20 Stems": 1599}'::jsonb,
    ARRAY['/src/assets/images/flower_chocolate_bouquet_1790174321849.jpg'],
    false,
    false,
    true,
    true,
    ARRAY['Anniversary', 'Valentine''s Specials', 'Birthday'],
    ARRAY['10 Stems', '20 Stems'],
    ARRAY['Fresh Floral Blend'],
    ARRAY['Calligraphy Message Card', 'Satin Ribbon Bow'],
    'Same-day delivery available across Jaipur'
),
(
    'bouquet-ferrero-fantasy',
    'ferrero-chocolate-bouquet',
    'Ferrero Rocher Chocolate Bouquet',
    'Chocolate Bouquets',
    'Hazelnut Truffles',
    'An edible arrangement of 16 premium Ferrero Rocher chocolates wrapped like blooming roses with golden glitter netting.',
    1199,
    '{"16 Pieces": 1199, "24 Pieces": 1699}'::jsonb,
    ARRAY['/src/assets/images/flower_chocolate_bouquet_1790174321849.jpg'],
    true,
    false,
    true,
    true,
    ARRAY['Anniversary', 'Birthday', 'Graduation', 'Valentine''s Specials'],
    ARRAY['16 Pieces', '24 Pieces'],
    ARRAY['Golden Hazelnut'],
    ARRAY['Custom Ribbon Message', 'Fairy Lights Addition'],
    'Available for scheduled delivery in Jaipur'
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    price = EXCLUDED.price,
    weight_prices = EXCLUDED.weight_prices,
    description = EXCLUDED.description;
